# Constants for these keys are found in the constants.rb file
#
# The protocol. This is used to construct the url for the link that appears in
# email notifications
protocol: http

# The host name. This is used to construct the url for the link that appears in
# email notifications
host: localhost

# The port number. This is used to construct the url for the link that appears in
# email notifications
port: 3000

# The email address of the administrator. This email will be used as the "from"
# address in emails sent by the application.
admin_email: admin@firehoze.com

# The default timezone for new users. Hint: execute the command:
#     rake time:zones:local
# to get a list of timezones local to your location
default_user_timezone: Eastern Time (US & Canada)

# The number of minutes to wait for a periodic job to complete. If the job does
# not complete in this timeframe, OpenMind will assume it is dead and initiate
# a recovery
periodic_job_timeout: 30

# The maximum video file upload size (in MB)
max_video_size: 500

# The maximum attachment file upload size (in MB)
max_attachment_size: 1

# Minimum credit purchase represents the fewest number of video credits that a user
# can purchase in one transaction
min_credit_purchase: 5

# The number of days to keep periodic jobs which have executed before purging them
keep_periodic_job_days: 7

# The number of days an unused credit will be good for without account activity before
# that credit expires
expire_credits_after_days: 365

# The number of days before expiration to warn the user that their credit is about to expire
warn_before_credit_expiration_days: 30

# The number of minutes to wait before warning the admin that a video has failed processing
zombie_video_process_minutes: 90

# The number of days before an unused gift certificate expires
gift_certificate_expires_days: 365

# The number of buy patterns to display (e.g., how many other lessons to show when telling the
# user "Users who viewed this lesson ultimately bought that lesson
number_of_buy_patterns_to_show: 30

# s3 directory name provides the name of the top level directory within Amazon buckets for storing videos
s3_directory: default

# If true, then users must enter a security code in order to register. This is used for beta instances
# which we don't want to open to the general public
restrict_registration: false

# Can users browse the site without logging in
allow_unrecognized_access: true

# allow crawlers. Valid values are "ALL" and "noindex"
crawler_access: ALL

# The id of the main firehoze instructor's group
firehoze_instructors_group_id: -1

# Require a registration code to become an instructor
restrict_instructor_signup: false

# Require a registration code to become an instructor
restrict_instructor_signup: false

# Canvas name in facebook
fb_canvas: fb_firehoze

# Facebook auth token
fb_auth_token: HZ24SE
