# Constants for these keys are found in the constants.rb file
#
# The protocol. This is used to construct the url for the link that appears in
# email notifications
protocol: http

# The host name. This is used to construct the url for the link that appears in
# email notifications
host: localhost

# The port number. This is used to construct the url for the link that appears in
# email notifications
port: 3000

# The email address of the administrator. This email will be used as the "from"
# address in emails sent by the application.
admin_email: admin@firehoze.com

# The default timezone for new users. Hint: execute the command:
#     rake time:zones:local
# to get a list of timezones local to your location
default_user_timezone: Eastern Time (US & Canada)

# The number of minutes to wait for a periodic job to complete. If the job does
# not complete in this timeframe, OpenMind will assume it is dead and initiate
# a recovery
periodic_job_timeout: 30

# The maximum video file upload size (in MB)
max_video_size: 500

# Minimum credit purchase represents the fewest number of video credits that a user
# can purchase in one transaction
min_credit_purchase: 5

# The number of days to keep periodic jobs which have executed before purging them
keep_periodic_job_days: 7

# The number of days an unused credit will be good for without account activity before
# that credit expires
expire_credits_after_days: 365

# The number of days before expiration to warn the user that their credit is about to expire
warn_before_credit_expiration_days: 10