# The protocol. This is used to construct the url for the link that appears in
# email notifications
protocol: http

# The host name. This is used to construct the url for the link that appears in
# email notifications
host: localhost

# The port number. This is used to construct the url for the link that appears in
# email notifications
port: 3000

# The email address of the administrator. This email will be used as the "from"
# address in emails sent by the application.
admin_email: admin@braindump.com