development:
  config_file: "/Users/Pete/Documents/Projects/RISE/src/Firehoze/config/development.sphinx.conf"
  bin_path: "/usr/local/bin"
  searchd_binary_name: searchd
  indexer_binary_name: indexer
  enable_star: true
  min_infix_len: 3
  morphology: stem_en
test:
  enable_star: true
  min_infix_len: 3
  morphology: stem_en
production:
  enable_star: true
  min_infix_len: 3
  morphology: stem_en
