development:
  enable_star: true
  min_infix_len: 3
  morphology: stem_en
test:
  enable_star: true
  min_infix_len: 3
  morphology: stem_en
production:
  enable_star: true
  min_infix_len: 3
  morphology: stem_en
