# The host name. This is used to construct the url for the link that appears in
# email notifications
host: 173.246.45.25

# The port number. This is used to construct the url for the link that appears in
# email notifications
port: 80