# The host name. This is used to construct the url for the link that appears in
# email notifications
host: 208.64.71.172

# The port number. This is used to construct the url for the link that appears in
# email notifications
port: 80